#!/usr/bin/env bash
# cloud-init user-data script
# SSH key is injected by Hetzner via --ssh-key flag
# "Started" notification is sent from hetzner.sh (instant, no cloud-init delay)

set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
export HOME=/root

# --- System ---
apt-get update
apt-get upgrade -y
apt-get install -y \
  git curl wget unzip build-essential \
  jq htop tmux

# --- Timezone ---
timedatectl set-timezone Europe/Kyiv

# --- Node.js 22 ---
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs

# --- AI CLI tools ---
npm install -g \
  @anthropic-ai/claude-code \
  @openai/codex

# --- Docker ---
apt-get install -y docker.io docker-compose-v2
systemctl enable --now docker

# --- .bashrc ---
cat >> /root/.bashrc <<'BASHRC'
alias ll='ls -la'
alias gs='git status'
BASHRC

# --- Clone repository ---
REPO="__REPOSITORY__"
GH_PAT="__GH_PAT__"

if [[ -n "${REPO}" && -n "${GH_PAT}" ]]; then
  REPO_NAME=$(basename "${REPO}")
  git clone "https://x-access-token:${GH_PAT}@github.com/${REPO}.git" "/root/${REPO_NAME}"

  git config --global credential.helper store
  echo "https://x-access-token:${GH_PAT}@github.com" > /root/.git-credentials
  chmod 600 /root/.git-credentials

  git config --global user.name "vnchnk"
  git config --global user.email "vnchnk@users.noreply.github.com"
fi

# --- devpanel (mobile-first dev dashboard) ---
git clone https://github.com/vnchnk/remote-vibe-panel.git /opt/remote-vibe-panel
cd /opt/remote-vibe-panel
PROJECT_DIR="/root/${REPO_NAME:-project}" docker compose up -d --build
cd /root

# --- Config ---
CLOUD_AUTO_DELETE="__CLOUD_AUTO_DELETE__"
CLOUD_TTL_MINUTES="__CLOUD_TTL_MINUTES__"
CLOUD_WARNING_MINUTES="__CLOUD_WARNING_MINUTES__"
HETZNER_API_TOKEN="__HETZNER_API_TOKEN__"
TELEGRAM_BOT_TOKEN="__TELEGRAM_BOT_TOKEN__"
TELEGRAM_CHAT_ID="__TELEGRAM_CHAT_ID__"
SESSION_ID="__SESSION_ID__"

# --- Save session info for notify.sh ---
mkdir -p /opt/remote-vibe-coder
cat > /opt/remote-vibe-coder/session.env <<ENVFILE
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
SESSION_ID=${SESSION_ID}
ENVFILE
chmod 600 /opt/remote-vibe-coder/session.env

# Save params (auto-generated by hetzner.sh)
cat > /opt/remote-vibe-coder/params.txt <<'PARAMS'
__PARAMS__
PARAMS

# --- notify.sh on server ---
cat > /opt/remote-vibe-coder/notify.sh <<'NOTIFY_SCRIPT'
__NOTIFY_SCRIPT__
NOTIFY_SCRIPT
chmod +x /opt/remote-vibe-coder/notify.sh

if [[ "${CLOUD_AUTO_DELETE}" == "true" && -n "${HETZNER_API_TOKEN}" ]]; then
  SERVER_ID=$(curl -s http://169.254.169.254/hetzner/v1/metadata/instance-id)

  # Save destruct timestamp for time_remaining()
  DESTRUCT_AT=$(( $(date +%s) + CLOUD_TTL_MINUTES * 60 ))
  echo "${DESTRUCT_AT}" > /tmp/destruct-at

  # --- Self-destruct script ---
  cat > /usr/local/bin/self-destruct.sh <<SCRIPT
#!/usr/bin/env bash
source /opt/remote-vibe-coder/session.env
export TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID SESSION_ID
/opt/remote-vibe-coder/notify.sh deleted
sleep 2
curl -s -X DELETE \
  -H "Authorization: Bearer ${HETZNER_API_TOKEN}" \
  "https://api.hetzner.cloud/v1/servers/${SERVER_ID}"
SCRIPT
  chmod +x /usr/local/bin/self-destruct.sh

  # --- Warning script ---
  cat > /usr/local/bin/self-destruct-warning.sh <<SCRIPT
#!/usr/bin/env bash
source /opt/remote-vibe-coder/session.env
export TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID SESSION_ID
/opt/remote-vibe-coder/notify.sh warning
SCRIPT
  chmod +x /usr/local/bin/self-destruct-warning.sh

  # --- Self-destruct service + timer ---
  cat > /etc/systemd/system/self-destruct.service <<EOF
[Unit]
Description=Auto-delete server

[Service]
Type=oneshot
ExecStart=/usr/local/bin/self-destruct.sh
EOF

  cat > /etc/systemd/system/self-destruct.timer <<EOF
[Unit]
Description=Auto-delete timer

[Timer]
OnActiveSec=${CLOUD_TTL_MINUTES}min
AccuracySec=1min

[Install]
WantedBy=timers.target
EOF

  # --- Warning timer ---
  WARNING_AT=$((CLOUD_TTL_MINUTES - CLOUD_WARNING_MINUTES))

  cat > /etc/systemd/system/self-destruct-warning.service <<EOF
[Unit]
Description=Warn before auto-delete

[Service]
Type=oneshot
ExecStart=/usr/local/bin/self-destruct-warning.sh
EOF

  cat > /etc/systemd/system/self-destruct-warning.timer <<EOF
[Unit]
Description=Auto-delete warning timer

[Timer]
OnActiveSec=${WARNING_AT}min
AccuracySec=1min

[Install]
WantedBy=timers.target
EOF

  systemctl daemon-reload
  systemctl enable --now self-destruct.timer
  if [[ "${WARNING_AT}" -ge 1 ]]; then
    systemctl enable --now self-destruct-warning.timer
    echo "Auto-delete: warning at ${WARNING_AT}min, delete at ${CLOUD_TTL_MINUTES}min"
  else
    echo "Auto-delete: delete at ${CLOUD_TTL_MINUTES}min (TTL < warning, warning sent immediately)"
    # Send warning immediately since TTL is shorter than warning period
    source /opt/remote-vibe-coder/session.env
    export TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID SESSION_ID
    /opt/remote-vibe-coder/notify.sh warning
  fi
fi

# --- Telegram bot polling service ---
if [[ -n "${TELEGRAM_BOT_TOKEN}" && -n "${TELEGRAM_CHAT_ID}" ]]; then
  cat > /etc/systemd/system/telegram-bot.service <<EOF
[Unit]
Description=Telegram bot callback handler
After=network-online.target

[Service]
Type=simple
EnvironmentFile=/opt/remote-vibe-coder/session.env
ExecStart=/opt/remote-vibe-coder/notify.sh poll
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now telegram-bot.service
fi

echo "Setup complete!"
